var greet  = require('./greet');
var greet2 = require('./greet2').greet;
var greet3 = require('./greet3');
var greet4 = require('./greet4');
var greet5 = require('./greet5');
var gtr = new greet4();
gtr.greet();
greet();
greet3.greet();
greet5.greet();